### ISSUE TITLE
Files that are not compliant with standardjs

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Javascript#139]
The following FilePaths fail `npx standard FilePath` and can not be fixed using the `--fix` option.
* https://standardjs.com
* [x] Javascript/linear-algebra-javascript/test/test.js
* [x] Javascript/linear-algebra-javascript/src/la_lib.js
* [ ] Remove [`|| true` from the `npx standard` command](https://github.com/TheAlgorithms/Javascript/blob/master/.github/workflows/nodejs.yml#L23)

---
* [x] Javascript/Ciphers/keyFinder.js #140
* [x] Javascript/Ciphers/vigenereCipher.js  #140
* [x] Javascript/Conversions/DecimalToHex.js  #140
* [x] Javascript/Data Structures/Graph/Graph.js #141
* [x] Javascript/Data Structures/Heap/MinPriorityQueue.js  #140
* [x] Javascript/Data Structures/Linked List/DoublyLinkedList.js  #140
* [x] Javascript/Data Structures/Queue/Queue.js  #140
* [x] Javascript/Data Structures/Stack/Stack.js  #140
* [x] Javascript/Data Structures/Tree/Binary Search Tree.js  #140
* [x] Javascript/Hashes/SHA256.js
* [x] Javascript/Search/linearSearch.js #143
* [x] Javascript/Sorts/TopologicalSort.js #141
* [x] Javascript/Sorts/bogoSort.js #150
* [x] Javascript/Sorts/bucketSort.js #141
* [x] Javascript/Sorts/combSort.js #141
* [x] Javascript/Sorts/cycleSort.js #141
* [x] Javascript/Sorts/heapSort.js  #150
* [x] Javascript/Sorts/selectionSort.js #141
* [x] Javascript/Sorts/wiggleSort.js  #150
* [x] Javascript/maths/DijkstraSmallestPath.js #147
* [x] Javascript/maths/abs.js #144 
* [x] Javascript/maths/factorial.js #145 
* [x] Javascript/maths/find_lcm.js #146
* [x] Javascript/maths/graph.js

**Comment by juliano-nunes** [comment]
Can I help with `Javascript/Ciphers/vigenereCipher.js` ?

**Comment by juliano-nunes** [comment]
Hey @itsvinayak, let me know if you need help :)

**Comment by cclauss** [comment]
This work should not all be done in one pull request (to have mercy on project maintainers) and should not all be done by one developer.  So if you wish to help, just fix a few files and submit a PR.  You do not need to wait for permission, just dig in.  ;-)

**Comment by juliano-nunes** [comment]
Ok @cclauss, thank you. I have opened a PR to fix the first ones (Ciphers, Conversions and Data Structures).

**Comment by cclauss** [comment]
Nice.  I look forward to seeing #140 reviewed and landed.  For future pull requests, to make this process easier for the reviewers, please try to do those files where standard just one or two objections first.  This will build momentum and should quickly get the long list down to a reasonable size.  For the files that require complex changes, please try to do one file per pull request.

Also, please look at https://github.com/TheAlgorithms/Javascript/actions to follow the standard testing progress.  Once all files are compliant, we should remove the `|| true` from our GitHub Action to mandate compliance on future PRs.  I added this at the end of our task list above.  Thanks!

**Comment by itsvinayak** [comment]
#140 has been merged and PR #141 has been created

**Comment by itsvinayak** [comment]
#147  is merged

**Comment by cclauss** [comment]
6 files left...  Do you know how to solve the problem with the sorts?

**Comment by cclauss** [comment]
@Nur69 Would you be willing to see if you can get Javascript/maths/graph.js to pass https://standardjs.com ?  I tried but was unable to get it to pass.

**Comment by itsvinayak** [comment]
> 6 files left... Do you know how to solve the problem with the sorts?

no, there is a problem with /linear-algebra-javascript/ and /sorts/  Algorithms

**Comment by cclauss** [comment]
Sort issue is https://www.google.com/search?q=Array+prototype+is+read+only%2C+properties+should+not+be+added.

**Comment by itsvinayak** [comment]
`Javascript/maths/graph.js` has been fixed in this [commit](https://github.com/TheAlgorithms/Javascript/commit/fc0aba01ace4b3e23e95d2439a185d89e2ec15f9)

**Comment by itsvinayak** [comment]
#152
```
 Javascript/linear-algebra-javascript/test/test.js
 Javascript/linear-algebra-javascript/src/la_lib.js
```
