### ISSUE TITLE
Doctest  required

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#142]
it will be good if algorithms have Doctest's  https://www.npmjs.com/package/doctest

**Comment by cclauss** [comment]
Which files is this in today?  It would be good to have a list of examples in this repo that contributors could review.

**Comment by itsvinayak** [comment]
@cclauss currently none of the files have Doctest

**Comment by cclauss** [comment]
#### Todos:
* [ ] Add doctests to at least two algorithms in this repo
* [ ]  Help at least one contributor to add doctests to a new algorithm contribution
* [ ] Discuss how difficult it was to complete 1. and 2.
* [ ] Decide if we should make doctests a _requirement_ of new contributions to this repo.

**Comment by itsvinayak** [comment]
more people of the community should discuss this issue

**Comment by nandanvasudevan** [comment]
Can we update the `package.json` with DocTest?
It's really easy to use especially for everything in this repo.

**Comment by cclauss** [comment]
Done in https://github.com/TheAlgorithms/Javascript/commit/4cbdc9e072ee2c373a2d0efacb501bd2c9db92a4

**Comment by nandanvasudevan** [comment]
>  Decide if we should make doctests a requirement of new contributions to this repo.

I think we should.

> Discuss how difficult it was to complete 1. and 2.

Shall I start writing a DocTest.md to help people add DocTests?

**Comment by remmaso** [comment]
In your document, open the “Insert” menu and then choose the “Drawing” command. In the Drawing window that opens, click the “Text Box” button on the toolbar at the top. Now, click and drag your mouse to create a text box in the space provided, and then add your desired tex

**Comment by marsonya** [comment]
hey @itsvinayak, i would like to help with adding doctest across the codebase. i have taken time to understand what doctest is and how it works. 
i am kinda new to open source contributions. so i was wondering if you could just give me a starting advice.
like do i start by add doctest to one algo first and submit pr and then add to others or like how should i begin?

**Comment by cclauss** [comment]
Open pull requests, not issues.  Only one file per PR so they are easy to review and land.

**Comment by marsonya** [comment]
understood. i will get to work right away.
thanks @cclauss

**Comment by itsvinayak** [comment]
hey, @marsonya can you help me with this #461 issue

**Comment by marsonya** [comment]
> hey, @marsonya can you help me with this #461 issue

Hey @itsvinayak, sure.
I will create a documentation for doctest.
Getting started right away...

**Comment by itsvinayak** [comment]
@marsonya thanks

**Comment by sukhpreetsekhon** [comment]
raised PR for doctest https://github.com/TheAlgorithms/Javascript/pull/502. Please review. Thanks!

**Comment by Khez** [comment]
@cclauss Can I keep on adding doctests in this format ? Already done a couple of the String files with #532 #533 #534 

Anything I need to change going forward with the rest of the files ?

I saw some of the algorithms have .test.js files, do we update them to doctest ?

**Comment by marsonya** [comment]
> hey, @marsonya can you help me with this #461 issue

Apologies for the delay. I have added doctest contribution guidelines. Kindly take a look and let me know if it works or if it needs ant changes.
Here's the PR #546

**Comment by mhihasan** [comment]
Some files have jest tests. Should we remove those jest tests and add doctest instead? [Personally, I would vote for jest, this doctest  package is not mature enough.]

**Comment by cclauss** [comment]
Please ___do not remove___ tests.  Contributors should have the freedom to test with doctests or jest.  Contibutors should not have the freedom to have no tests at all.

**Comment by raklaptudirm** [comment]
@cclauss We still haven't settled on the issues of doctests failing because some files have none.

**Comment by Ameya101** [comment]
Add it in Contributing.md dont create a new file

**Comment by defaude** [comment]
@raklaptudirm I recommend we close this issue in favour of #742
