### ISSUE TITLE
Algorithm needed for graphs data structures

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#195]
some algorithms :1st_place_medal: 

- [x] Add Kruskal's Algorithm to find Minimum Spanning Tree
- [x] Algorithm to find the Minimum Spanning Tree using Prims Algorithm #227 
- [x] Algorithm to find connected components using Disjoint sets
- [x] Algorithm to find connected components in the graph using depth-first search  #223 
- [x] Depth First Search Algorithms #199 

---
feel free to add more algorithms in the list
thank you, @itsvinayak

**Comment by itsvinayak** [comment]
@ayaankhan98

**Comment by ayaankhan98** [comment]
i opened seprate issue for each one because if someone wishes to work on only one algorithm then it will be easy to track. well i have no problem with this too

**Comment by itsvinayak** [comment]
> i opened seprate issue for each one because if someone wishes to work on only one algorithm then it will be easy to track. well i have no problem with this too

@ayaankhan98  opening many issues for the same thing doesn't seem like a nice idea

**Comment by itsvinayak** [comment]
@ayaankhan98 we need help with this #168 
please have a look

**Comment by ayaankhan98** [comment]
@itsvinayak  are you working on this?

**Comment by itsvinayak** [comment]
> @itsvinayak are you working on this?

 currently, I am not working with this issue, you can move forward if you want.
@ayaankhan98

**Comment by ayaankhan98** [comment]
i just asked for curiosity

**Comment by comradesurendra** [comment]
I have implemented the DFS part. Have a look at it....!

**Comment by itsvinayak** [comment]
@comradesurendra 
Can you mention your PR here 

thank you

**Comment by TangibleDream** [comment]
@itsvinayak Would #222 be considered a graph calculation?

**Comment by itsvinayak** [comment]
> @itsvinayak Would #222 be considered a graph calculation?

no its a maths algorithm examples

**Comment by itsvinayak** [comment]
hey @ruppysuppy, can you work with any of the algorithm mentioned above

**Comment by ruppysuppy** [comment]
Ok, I'll add the algorithms (except the one using disjoint sets)
